export const colors = {
    INCREMENT_RED: "INCREMENT_RED",
    DECREMENT_RED: "DECREMENT_RED",
    INCREMENT_GREEN: "INCREMENT_GREEN",
    DECREMENT_GREEN: "DECREMENT_GREEN",
     INCREMENT_BLUE: "INCREMENT_BLUE",
    DECREMENT_BLUE: "DECREMENT_BLUE",
  };